# Unique and deduplicated list of French Tech and Data channels.

CHANNELS = [
    {"channel_id": "UCj_iGliGCkLcHSZ8eqVNPDQ", "channel_name": "Grafikart.fr"},
    {"channel_id": "UCLOAPb7ATQUs_nDs9ViLcMw", "channel_name": "Benjamin Code"},
    {"channel_id": "UCjDg7LaaMzmuhj6I1jTzb1Q", "channel_name": "Développeur Libre"},
    {"channel_id": "UC5cs06DgLFeyLIF_II7lWCQ", "channel_name": "Cookie connecté"},
    {"channel_id": "UC9RqnWGripL5L3lxH-fEZjg", "channel_name": "Louis-Nicolas • Believemy"},
    {"channel_id": "UCHGLV13U7YRbjrKpqfbtyYg", "channel_name": "From Scratch - Le développement Web de zéro"},
    {"channel_id": "UC5HDIVwuqoIuKKw-WbQ4CvA", "channel_name": "Melvynx"},
    {"channel_id": "UCzuaB4F2znrMggxcwUuVhAw", "channel_name": "LES TEACHERS DU NET"},
    {"channel_id": "UC7BNBNLwMF8GjgXLDP8PWQw", "channel_name": "Mike Codeur"},
    {"channel_id": "UCmpptkXu8iIFe6kfDK5o7VQ", "channel_name": "Machine Learnia"},
    {"channel_id": "UCXPsm8oMQoVoQI_0NL4Db7w", "channel_name": "DataGen - Robin Conquet"},
    {"channel_id": "UC94UeaPuTt_L51RkDxj9d_w", "channel_name": "Yassine Sdiri"},
    {"channel_id": "UCIHVyohXw6j2T-83-uLngEg", "channel_name": "Graven - Développement"},
    {"channel_id": "UCo2zkK2d_frGSXctIkftALw", "channel_name": "Docstring"},
    {"channel_id": "UCs_AZuYXi6NA9tkdbhjItHQ", "channel_name": "xavki"},
    {"channel_id": "UCVRJ6D343dX-x730MRP8tNw", "channel_name": "cocadmin"},
    {"channel_id": "UC_grjqug_eF6bRS_fVezK-A", "channel_name": "Hafnium - Sécurité informatique"},
    {"channel_id": "UCIJTq0nGrgkGMy1xJL_YppQ", "channel_name": "IT-Connect - Florian"},
    {"channel_id": "UCxrT9QLqHx5fWeSaL8MoJLQ", "channel_name": "DevArt - Réussir dans la tech"},
    {"channel_id": "UCBdbSVXZNwNDOK8FHJlfilw", "channel_name": "Enzo - Les WebMasters 2.0"},
    {"channel_id": "UCDKPGD9T00eS_l--D_DRTUQ", "channel_name": "Adrien Linuxtricks"},
    {"channel_id": "UCWedHS9qKebauVIK2J7383g", "channel_name": "Underscore_"},
    {"channel_id": "UCnnYqSNKKygemgmxC9PyLTw", "channel_name": "Ludo Salenne"},
    {"channel_id": "UCxx03UqvjTy9w8iomLwTSuQ", "channel_name": "Henri · ExplorIA"},
    {"channel_id": "UCgJERWtcvu-JiPq5wBkYF1g", "channel_name": "DevTheory"},
    {"channel_id": "UCA_7ewGx2phSG62uCJJdsrw", "channel_name": "Justine Morin"},
    {"channel_id": "UCWKyakTmFf38Sv0cD8MNzzg", "channel_name": "Le Frère Codeur"},
    {"channel_id": "UCrgBTSEQo13M5P7O9Rf7-oQ", "channel_name": "L'envers du décode"},
    {"channel_id": "UCslDlZ9q6IlJklvQlEgbsGQ", "channel_name": "MXR CODES"},
    {"channel_id": "UCQqCRXWEYwvLH3Ws5n4X5Jg", "channel_name": "Naier Saidane"},
    {"channel_id": "UCnblkfNg9uYsToP2hLXSjWA", "channel_name": "Data From Scratch - Willis"},
    {"channel_id": "UCoincaYNa5FBdi-I5oqHAMw", "channel_name": "LeCoinStat"},
    {"channel_id": "UClwag9MZmEsrGueQlHX_fqg", "channel_name": "Dataseito"},
    {"channel_id": "UCO6P25qG9O4f6Bk9UKMLAjw", "channel_name": "Pentiminax"},
    {"channel_id": "UCQnDt41NOE4m_m3quKt0JQw", "channel_name": "ViDev"},
    {"channel_id": "UCzsIm81pLYinjhfjDsFZ-aA", "channel_name": "Parfaitement Web"},
    {"channel_id": "UCE0rrl2C0vBM81bdYVnajWQ", "channel_name": "Donald Programmeur"},
    {"channel_id": "UCUSRY5EcZAhSbz1Q1QuQw0w", "channel_name": "Boris ('PrimFX')"},
    {"channel_id": "UCMFbNXUkjSUJ6WC20tGTzJg", "channel_name": "École du Web"},
    {"channel_id": "UCUjo_IKa9Cqkx_x-rMly8MA", "channel_name": "getCodingKnowledge"},
    {"channel_id": "UC1VLE5isKBsZbkT2KvLKSLA", "channel_name": "Johan : Solutions Digitales"},
    {"channel_id": "UCnEHCrot2HkySxMTmDPhZyg", "channel_name": "Defend Intelligence"},
]
